# .readthedocs.yml
# Read the Docs configuration file

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - python -m pip install -c reqs/constraints.txt --no-binary=plover-stroke plover-stroke
      - python -m pip install -c reqs/constraints.txt -r reqs/dist.txt
      - python -m pip install -c reqs/constraints.txt -e .
  apt_packages:
    - python3-dev
    - build-essential

python:
  install:
    - requirements: doc/requirements.txt

sphinx:
  configuration: doc/conf.py
